version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    restart: always
    ports:
      - "8180:8180"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://host.docker.internal:3306/dormitory
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MariaDBDialect
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
