spring:
  application:
    name: backend
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mariadb://localhost:3306/dormitory
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
#  liquibase:
#    enabled: true
#    change-log: classpath:db/changelog/changelog-master.xml

server:
  port: 8180
  servlet:
    context-path: /api/v1
